name = "new-lmage"
compatibility_date = "2023-01-01"
main = "build/index.js"

[vars]
# 生产环境环境变量
TG_Bot_Token = "8859657937:AAGo-u8oMjjXV-257hvBAkLxXBPffbjNzec"
TG_Chat_ID = "-1002509744447"
JWT_SECRET = "laowang-hardcore-jwt-secret-key-9527"

[[d1_databases]]
binding = "DB"
database_name = "image"
database_id = "484dd7ca-eb1f-41bf-b913-9b1edcc36da1"

[build]
command = "node build-platform.js"

[site]
bucket = "./client/dist"